from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

from app.services.research_lineage import core_darkflow_v2_lineage, legacy_baseline_v0_lineage


@dataclass(frozen=True)
class DarkflowIndicatorRule:
    official_key: str
    official_name: str
    internal_keys: tuple[str, ...]
    family: str
    primary_roles: tuple[str, ...]
    long_rule: str
    short_rule: str
    stop_rule: str
    target_rule: str
    blocker_rule: str
    confirmation_required: tuple[str, ...]
    single_trigger_allowed: bool
    implementation_status: str


OFFICIAL_INDICATOR_RULES: dict[str, DarkflowIndicatorRule] = {
    "smart_money_cost": DarkflowIndicatorRule(
        "smart_money_cost",
        "趋势成本带 (Trend Cost)",
        ("smart_money_cost",),
        "cost_structure",
        ("direction", "entry", "stop", "target", "invalidation"),
        "价格首次回踩或跌入绿色吸筹成本带时，顺长期方向做多，止损放绿带下沿外侧。",
        "价格反弹首次触碰红色派发压制带时，顺长期方向做空，止损放红带上沿外侧。",
        "实体跌破绿色带或实体突破红色带，原方向成本防线失效。",
        "相邻反向成本带、清算磁吸区或历史撑压区作为目标。",
        "实体破带且未收回时禁止继续按原方向抄底/摸顶。",
        ("cross_exchange_resonance", "imbalance", "liq_heatmap"),
        False,
        "scoring_baseline_plus_playbook_v1",
    ),
    "liq_heatmap": DarkflowIndicatorRule(
        "liq_heatmap",
        "清算痛点地图 (Liquidation Heatmap)",
        ("liq_heatmap",),
        "liquidity",
        ("target", "reversal", "stop_context"),
        "下方红色多头清算带被影线刺穿并快速收回时，视为主力吃掉多头止损后的反向做多信号。",
        "上方绿色空头清算带被影线刺穿并快速回落时，视为主力吃掉空头止损后的反向做空信号。",
        "反向接针的止损放在刺穿针尖外侧。",
        "顺势持仓时，最近且最浓的上方/下方清算带是磁吸止盈目标。",
        "刚刺穿并收回清算带后，禁止顺刺穿方向追单。",
        ("liquidity_sweep", "imbalance", "micro_poc"),
        False,
        "scoring_target_and_playbook_v1",
    ),
    "absolute_zones": DarkflowIndicatorRule(
        "absolute_zones",
        "密集博弈 (Absolute Zones)",
        ("absolute_zones",),
        "orderflow_structure",
        ("support_resistance", "breakout"),
        "底部密集绿色箭头且跌势停滞时，可作为左侧抄底候选。",
        "顶部密集红色箭头且冲高被压回时，可作为左侧摸顶候选。",
        "密集博弈区被实体反向突破，原防守方失效。",
        "突破密集博弈区后，以失败方止损踩踏方向作为顺势目标。",
        "箭头混杂但未突破时避免追单，只做区间反应。",
        ("inst_choch", "power_imbalance", "cross_exchange_resonance"),
        False,
        "official_rule_pending_collection_mapping",
    ),
    "fvg": DarkflowIndicatorRule(
        "fvg",
        "筹码真空区 (FVG)",
        ("fair_value_gap", "fvg"),
        "vacuum",
        ("magnet", "entry", "acceleration"),
        "暴涨留下的淡青色真空区被回补到下沿并出现支撑确认时做多。",
        "暴跌留下的淡紫红色真空区被反弹回补到上沿并出现压制确认时做空。",
        "缺口被完全穿透后仍无反应，原真空支撑/阻力失效。",
        "真空区对侧边界或下一个筹码峰作为目标。",
        "价格高位远离真空区时禁止追多，等待磁吸回补。",
        ("liq_vacuum", "inst_choch", "imbalance"),
        False,
        "experiment_feature_ready",
    ),
    "cross_exchange_resonance": DarkflowIndicatorRule(
        "cross_exchange_resonance",
        "主力大单行动 (Whale Action)",
        ("cross_exchange_resonance",),
        "orderflow",
        ("confirmation", "breakout"),
        "横盘或突破阻力时出现多所共振绿色大单，确认真突破做多。",
        "跌破支撑时出现多所共振红色大单，确认真跌破做空。",
        "突破后无后续订单流或方向反转，触发确认失效。",
        "结合清算带、FVG 或趋势撑压空白区作为目标。",
        "没有大单共振的孤立拉升/砸盘，按假突破降权。",
        ("inst_choch", "imbalance", "power_imbalance"),
        False,
        "scoring_confirmation",
    ),
    "cascade_liquidation": DarkflowIndicatorRule(
        "cascade_liquidation",
        "连环爆仓区 (Cascade Liquidation Zones)",
        ("cascade_liquidation_zones", "cascade_liquidation"),
        "liquidity",
        ("reversal", "target"),
        "急跌触碰下方红色连环爆仓区时，优先等待针尖反转做多，不追空。",
        "急涨触碰上方绿色连环爆仓区时，优先等待针尖反转做空，不追多。",
        "反向接针止损放爆仓针尖外侧。",
        "爆仓区本身是顺势磁吸目标，触发后应快速减仓或保本。",
        "价格冲向雷区时禁止同向追单。",
        ("liq_heatmap", "liquidity_sweep", "power_imbalance"),
        False,
        "experiment_feature_ready",
    ),
    "retail_stop_loss": DarkflowIndicatorRule(
        "retail_stop_loss",
        "散户止损点 (Retail Stop Loss)",
        ("retail_stop_loss",),
        "liquidity",
        ("magnet", "breakout", "reversal"),
        "下方红带被扫后收回，可作为多头反向接针；上方绿带被实体打断后可顺势追多。",
        "上方绿带被扫后回落，可作为空头反向接针；下方红带被实体打断后可顺势追空。",
        "反向交易止损放扫损针尖外。",
        "深色散户止损带是主力洗盘磁吸目标。",
        "带子未断时不要把它当普通阻力/支撑硬追。",
        ("liq_heatmap", "liquidity_sweep", "imbalance"),
        False,
        "experiment_feature_ready",
    ),
    "max_pain_drawdown": DarkflowIndicatorRule(
        "max_pain_drawdown",
        "极限洗盘深度 (Max Pain)",
        ("max_pain", "max_pain_drawdown"),
        "liquidity",
        ("stop", "add", "invalidation"),
        "多头洗盘色带内保持底仓，针尖触及下方实线边界可小仓加多。",
        "空头洗盘色带内保持底仓，针尖触及上方实线边界可小仓加空。",
        "实体击穿洗盘极限边界，说明洗盘失败，必须止损。",
        "配合趋势目标或清算磁吸区止盈。",
        "实体破极限边界后禁止继续按洗盘解释加仓。",
        ("smart_money_cost", "liquidity_sweep"),
        False,
        "catalog_only_pending_collection",
    ),
    "trend_roi_exhaustion": DarkflowIndicatorRule(
        "trend_roi_exhaustion",
        "未来收益预期 (Trend ROI)",
        ("trend_roi", "trend_roi_exhaustion"),
        "lifecycle",
        ("target", "exit", "blocker"),
        "多头触及平均目标先减仓，触及极限目标禁止追多并准备反转。",
        "空头触及平均目标先减仓，触及极限目标禁止追空并准备反转。",
        "极限目标被触及后，原顺势新开逻辑失效。",
        "平均线与极限线分别作为分批止盈与最终止盈。",
        "触及极限线后禁止顺势开新仓。",
        ("trend_exhaustion", "volume_exhaustion_threshold"),
        False,
        "catalog_only_pending_collection",
    ),
    "max_drawdown_tolerance": DarkflowIndicatorRule(
        "max_drawdown_tolerance",
        "涨跌极限 (Max Drawdown Tolerance)",
        ("max_drawdown_tolerance",),
        "lifecycle",
        ("trailing_stop", "exit"),
        "多头趋势中以动态阶梯线作为移动止损，黄钉出现立即止盈/退出。",
        "空头趋势中以动态阶梯线作为移动止损，黄钉出现立即止盈/退出。",
        "K 线刺穿极限防线并出现警告钉，趋势持仓失效。",
        "移动护城河用于吃完整段趋势。",
        "黄钉出现后禁止继续原方向加仓。",
        ("trailing_vwap", "trend_exhaustion"),
        False,
        "catalog_only_pending_collection",
    ),
    "time_exhaustion_window": DarkflowIndicatorRule(
        "time_exhaustion_window",
        "趋势时间极限 (Time Exhaustion)",
        ("time_exhaustion", "time_exhaustion_window"),
        "lifecycle",
        ("exit", "blocker"),
        "多头趋势越过平均寿命减仓，撞黄色死亡线全平并禁止追多。",
        "空头趋势越过平均寿命减仓，撞黄色死亡线全平并禁止追空。",
        "死亡线之后原趋势时间假设失效。",
        "用于时间止盈，不用于常规目标价。",
        "死亡线之后的顺势突破默认按高风险假突破处理。",
        ("trend_roi_exhaustion", "trend_exhaustion"),
        False,
        "catalog_only_pending_collection",
    ),
    "volume_exhaustion_threshold": DarkflowIndicatorRule(
        "volume_exhaustion_threshold",
        "趋势资金阀值 (Volume Exhaustion)",
        ("volume_exhaustion", "volume_exhaustion_threshold"),
        "lifecycle",
        ("exit", "blocker"),
        "多头资金消耗接近极限时止盈，不再追多。",
        "空头资金消耗接近极限时止盈，不再追空。",
        "黄色水滴警告出现后，原方向资金续航假设失效。",
        "资金阈值主要用于止盈和反转预警。",
        "油表见底后禁止原方向新开。",
        ("trend_exhaustion", "trend_roi_exhaustion"),
        False,
        "catalog_only_pending_collection",
    ),
    "inst_choch": DarkflowIndicatorRule(
        "inst_choch",
        "破坏与突破 (Inst CHoCH)",
        ("inst_choch",),
        "structure_break",
        ("breakout", "confirmation", "retest_entry"),
        "CHoCH_Bullish 代表资金打穿空头防线，等待回踩虚线附近做多。",
        "CHoCH_Bearish 代表资金打穿多头防线，等待回踩虚线附近做空。",
        "回踩后重新跌回/涨回被突破防线内，突破失效。",
        "突破后的 FVG、清算带或撑压空白区作为目标。",
        "闪电出现后禁止盲目追高追低，优先等回踩。",
        ("cross_exchange_resonance", "power_imbalance"),
        False,
        "experiment_feature_ready",
    ),
    "ob_decay": DarkflowIndicatorRule(
        "ob_decay",
        "订单墙衰减 (OB Decay)",
        ("ob_decay",),
        "structure_decay",
        ("entry", "breakout_filter"),
        "深色订单墙初次/二次回踩可做多反弹；墙体变淡后等待向下/向上突破确认。",
        "深色上方订单墙初次/二次触碰可做空反弹；墙体变淡后等待突破。",
        "订单墙颜色极淡或多次测试后，反弹逻辑失效。",
        "薄墙被击穿后，顺突破方向看下一个暗流区。",
        "薄墙阶段禁止继续做反弹。",
        ("trend_price", "inst_choch", "power_imbalance"),
        False,
        "catalog_only_pending_collection",
    ),
    "micro_poc": DarkflowIndicatorRule(
        "micro_poc",
        "微观成本线 (Micro POC)",
        ("micro_poc",),
        "cost_structure",
        ("entry", "stop", "retest"),
        "价格首次快速回调触及下方绿色 POC 射线时，做护盘反弹多单。",
        "价格反弹触及上方红色 POC 射线时，做压制回落空单。",
        "确认实体破线且无法吸回时，局部成本防线失效。",
        "以相邻清算带、撑压区或下一个 POC/HVN 作为目标。",
        "非首次触达或已多次失效的 POC 降权。",
        ("trend_price", "liq_heatmap", "imbalance"),
        False,
        "feature_research_ready_playbook_v1",
    ),
    "fair_value": DarkflowIndicatorRule(
        "fair_value",
        "真实价值走势 (Fair Value)",
        ("fair_value",),
        "value_divergence",
        ("filter", "reversal"),
        "价格创新低但真实价值线抬高，说明底背离，可作为抄底过滤确认。",
        "价格创新高但真实价值线下行，说明顶背离，可作为摸顶过滤确认。",
        "价值线继续顺价格方向发散，则背离假设失效。",
        "目标是价格向价值线回归。",
        "价格与价值线明显背离反向时，禁止追原方向。",
        ("imbalance", "poc_shift"),
        False,
        "official_rule_pending_collection_mapping",
    ),
    "inst_volume_profile": DarkflowIndicatorRule(
        "inst_volume_profile",
        "筹码分布 (Volume Profile)",
        ("inst_volume_profile",),
        "volume_profile",
        ("support_resistance", "acceleration"),
        "回踩下方机构筹码峰时做多反弹。",
        "反弹上方机构筹码峰时做空回落。",
        "筹码峰被实体穿透且无回收，防线失效。",
        "筹码低谷会快速穿越，下一个筹码峰是目标。",
        "密集筹码峰前不追突破，等确认穿透。",
        ("trend_purity", "hvn_nodes", "power_imbalance"),
        False,
        "feature_research_ready_playbook_v1",
    ),
    "trend_price": DarkflowIndicatorRule(
        "trend_price",
        "趋势撑压 (Trend Price)",
        ("trend_price",),
        "cost_structure",
        ("entry", "target", "acceleration"),
        "价格回落到右侧绿色支撑区域时低吸做多。",
        "价格反弹到右侧红色压制区域时高抛/做空。",
        "右侧支撑/阻力被实体穿越后，原区间属性失效或反转。",
        "撑压空白区支持单边加速，到下一个色带止盈。",
        "前方密集红绿带时降低追单权重。",
        ("micro_poc", "ob_decay", "imbalance"),
        False,
        "feature_research_ready_playbook_v1",
    ),
    "trend_purity": DarkflowIndicatorRule(
        "trend_purity",
        "趋势筹码纯度 (Trend Purity)",
        ("trend_purity",),
        "volume_profile",
        ("quality_filter", "breakout"),
        "高纯绿色支撑峰回踩可做多。",
        "高纯红色压制峰反弹可做空。",
        "高纯区被反向实体突破，触发失败方踩踏，原防线失效。",
        "反向突破高纯区后，看踩踏方向延伸目标。",
        "低纯度筹码区不能当强支撑/阻力。",
        ("inst_volume_profile", "power_imbalance"),
        False,
        "experiment_feature_ready",
    ),
    "poc_shift": DarkflowIndicatorRule(
        "poc_shift",
        "均价重心偏移 (POC Shift)",
        ("poc_shift",),
        "value_divergence",
        ("direction", "reversal", "filter"),
        "底部横盘中当前 POC 上穿历史基准，说明暗中吸筹，偏多。",
        "高位横盘中当前 POC 下穿历史基准，说明暗中派发，偏空。",
        "POC 重新反穿基准线，原吸筹/派发判断失效。",
        "乖离过大后，目标看 POC 向基准回归。",
        "POC 乖离过大时禁止追当前短线极端方向。",
        ("fair_value", "imbalance"),
        False,
        "catalog_only_pending_collection",
    ),
    "trailing_vwap": DarkflowIndicatorRule(
        "trailing_vwap",
        "趋势动态防线 (Trailing VWAP)",
        ("trailing_vwap",),
        "cost_structure",
        ("trailing_stop", "breakout"),
        "绿梯上行时逢低做多，止损跟随绿梯下方。",
        "红梯下行时逢高做空，止损跟随红梯上方。",
        "价格有效跌破绿梯或突破红梯，持仓防线失效。",
        "沿动态防线推损吃趋势，直到破梯退出。",
        "红绿梯极度收敛前不提前猜方向，等待带量突破。",
        ("inst_vwap", "trend_price", "cross_exchange_resonance"),
        False,
        "catalog_only_pending_collection",
    ),
    "trend_saturation": DarkflowIndicatorRule(
        "trend_saturation",
        "趋势进度条 (Trend Saturation)",
        ("trend_saturation",),
        "lifecycle",
        ("patience_filter", "breakout_watch"),
        "吸筹进度低时不重仓追入，进度接近完成后等待向上突破。",
        "派发进度低时不重仓追空，进度接近完成后等待向下突破。",
        "进度方向改变或突破失败，原蓄势判断失效。",
        "进度拉满后配合突破确认进入趋势目标。",
        "进度太低时禁止把震荡误判为马上起飞。",
        ("inst_choch", "cross_exchange_resonance"),
        False,
        "catalog_only_pending_collection",
    ),
    "liq_vacuum": DarkflowIndicatorRule(
        "liq_vacuum",
        "流动性黑洞预警 (Liquidity Vacuum)",
        ("liquidity_vacuum", "liq_vacuum"),
        "vacuum",
        ("acceleration", "risk_filter"),
        "向上突破后上方是真空区，可持有或追随单边加速。",
        "跌破支撑后下方是真空区，必须止损或顺势做空。",
        "重新回到真空区外侧，单边加速假设失效。",
        "真空区对侧或下一个筹码峰作为目标。",
        "高位跌入下方黑洞时禁止扛单。",
        ("fvg", "inst_choch", "volume_profile"),
        False,
        "experiment_feature_ready",
    ),
    "inst_vwap": DarkflowIndicatorRule(
        "inst_vwap",
        "机构均价 (Inst VWAP)",
        ("inst_vwap",),
        "macro_cost",
        ("direction", "macro_filter"),
        "价格稳在机构 VWAP 上方，市场处于机构盈利多头环境，以低多为主。",
        "价格跌破机构 VWAP，市场转弱或空头主导，以高空为主。",
        "有效跌破/突破蓝线后，原牛熊环境判断切换。",
        "大级别恐慌回踩蓝线可作为长线目标/支撑。",
        "蓝线下方禁止用牛市思维追多。",
        ("smart_money_cost", "trailing_vwap"),
        False,
        "feature_research_ready_playbook_v1",
    ),
    "imbalance": DarkflowIndicatorRule(
        "imbalance",
        "多空失衡能量条 (Imbalance)",
        ("imbalance",),
        "orderflow",
        ("confirmation", "divergence"),
        "价跌但能量条大绿，说明主力吸筹，可确认抄底/反转多。",
        "价涨但能量条发红或绿柱极短，说明诱多派发，可确认做空/退出。",
        "能量条与预期方向连续背离，原信号失效。",
        "用于确认，不单独给目标。",
        "价格漂亮但资金反向时禁止追。",
        ("liquidity_sweep", "micro_poc", "cross_exchange_resonance"),
        False,
        "scoring_confirmation",
    ),
    "power_imbalance": DarkflowIndicatorRule(
        "power_imbalance",
        "多空力量悬殊比 (Power Imbalance)",
        ("power_imbalance",),
        "orderflow",
        ("breakout_confirmation", "do_not_fade"),
        "突破阻力时绿柱极端放大，顺势追多，不摸顶。",
        "跌破支撑时红柱极端放大，顺势追空，不抄底。",
        "极端碾压消失且价格回撤突破位，趋势确认失效。",
        "目标看清算带或真空区。",
        "极端柱方向明确时禁止逆势摸顶/抄底。",
        ("inst_choch", "cross_exchange_resonance"),
        False,
        "official_rule_pending_collection_mapping",
    ),
    "trend_exhaustion": DarkflowIndicatorRule(
        "trend_exhaustion",
        "能量耗竭 (Trend Exhaustion)",
        ("trend_exhaustion",),
        "lifecycle",
        ("reversal", "exit", "blocker"),
        "低位红柱极端放大但价格不再创新低，说明空头耗竭，可抄底做多。",
        "高位绿柱极端放大但价格不再有效创新高，说明多头耗竭，可摸顶做空。",
        "价格继续放量有效突破，耗竭反转假设失效。",
        "耗竭用于退出和反转，不直接给远端目标。",
        "耗竭反向明显时禁止追原方向。",
        ("liq_heatmap", "imbalance", "time_exhaustion_window"),
        False,
        "scoring_filter_plus_playbook_v1",
    ),
    "liquidation_fuel": DarkflowIndicatorRule(
        "liquidation_fuel",
        "燃料库清算地图 (Liquidation Fuel)",
        ("liquidation_fuel",),
        "liquidity",
        ("target", "magnet"),
        "上方燃料带深厚且下方稀薄，做多持仓目标看上方燃料。",
        "下方燃料带深厚且上方稀薄，做空持仓目标看下方燃料。",
        "燃料带被点燃后，应视为目标已达，继续持仓需新证据。",
        "最深燃料带是主力点燃爆仓的止盈目标。",
        "靠近燃料带后禁止无保护继续贪。",
        ("liq_heatmap", "retail_stop_loss"),
        False,
        "feature_research_ready_playbook_v1",
    ),
    "hvn_nodes": DarkflowIndicatorRule(
        "hvn_nodes",
        "真实换手率节点 (HVN)",
        ("hvn_nodes",),
        "volume_profile",
        ("support_resistance", "target"),
        "回踩下方 HVN 射线时做多反弹。",
        "反弹上方 HVN 射线时做空回落。",
        "HVN 被实体穿透且不回收，节点防线失效。",
        "下一个 HVN 或清算带作为目标。",
        "突破节点前不把它当成空白区。",
        ("micro_poc", "trend_price", "trend_purity"),
        False,
        "feature_research_ready_playbook_v1",
    ),
    "liquidity_sweep": DarkflowIndicatorRule(
        "liquidity_sweep",
        "流动性猎杀 (Liquidity Sweep)",
        ("liquidity_sweep",),
        "liquidity",
        ("entry", "reversal", "stop"),
        "底部猎杀血滴：向下刺破前低后快速收回，做多，止损放针尖下方。",
        "顶部猎杀血滴：向上刺破前高后快速回落，做空，止损放针尖上方。",
        "再次跌破/突破针尖，猎杀反转失效。",
        "目标看反向清算带、Micro POC 或趋势撑压。",
        "血滴后禁止顺刺穿方向追。",
        ("liq_heatmap", "imbalance", "micro_poc"),
        True,
        "feature_research_ready_playbook_v1",
    ),
    "time_heatmap": DarkflowIndicatorRule(
        "time_heatmap",
        "资金时间热力图 (Time Heatmap)",
        ("time_heatmap",),
        "session_filter",
        ("filter", "breakout_quality"),
        "高活跃时段出现多头突破更可信。",
        "高活跃时段出现空头跌破更可信。",
        "垃圾时间突破默认降低可信度。",
        "不直接给目标价，只给时段质量。",
        "低活跃垃圾时间的突破禁止直接追。",
        ("inst_choch", "cross_exchange_resonance"),
        False,
        "official_rule_pending_collection_mapping",
    ),
}


OFFICIAL_TO_INTERNAL: dict[str, tuple[str, ...]] = {
    key: rule.internal_keys for key, rule in OFFICIAL_INDICATOR_RULES.items()
}


def darkflow_rulebook() -> dict[str, Any]:
    return {
        "strategy_family": "darkflow_tutorial_semantics_v1",
        "source": "dash.hfd.fund/pro tutorial indicatorConfigs",
        "indicator_count": len(OFFICIAL_INDICATOR_RULES),
        "policy": {
            "baseline_v0_status": "infrastructure_and_control_only",
            "no_opening_from_unmapped_indicators": True,
            "requires_playbook_before_scoring": True,
            "lineage": core_darkflow_v2_lineage(),
            "baseline_v0_lineage": legacy_baseline_v0_lineage(),
        },
        "official_to_internal": {key: list(value) for key, value in OFFICIAL_TO_INTERNAL.items()},
        "rules": [asdict(rule) for rule in OFFICIAL_INDICATOR_RULES.values()],
    }


def official_rule_for_internal_indicator(indicator: str) -> DarkflowIndicatorRule | None:
    for rule in OFFICIAL_INDICATOR_RULES.values():
        if indicator in rule.internal_keys:
            return rule
    return None
